services:
  - type: web
    name: lunch-app
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --config gunicorn.conf.py backend.app.wsgi:app
    pythonVersion: 3.12.7
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: PYTHONPATH
        value: /opt/render/project/src
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: ${POSTGRES_URL}
      - key: SECRET_KEY
        fromService:
          type: secret
          name: lunch-app-secret-key
      - key: JWT_SECRET_KEY
        fromService:
          type: secret
          name: lunch-app-jwt-secret-key
      - key: MAIL_USERNAME
        fromService:
          type: secret
          name: lunch-app-mail-username
      - key: MAIL_PASSWORD
        fromService:
          type: secret
          name: lunch-app-mail-password
      - key: INQUIRY_EMAIL
        fromService:
          type: secret
          name: lunch-app-inquiry-email
      - key: ALLOWED_ORIGINS
        value: https://lunch-app-frontend.onrender.com,http://localhost:3000,http://localhost:19006,http://localhost:8081
