services:
  - type: web
    name: lunch-app
    env: docker
    dockerfilePath: ./Dockerfile
    envVars:
      - key: PYTHON_VERSION
        value: 3.12.7
      - key: PYTHONPATH
        value: /app
