version: '3.8'

services:
  redis:
    image: redis:7-alpine
    container_name: lunch_app_redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    command: redis-server --appendonly yes
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 10s
      retries: 3

  # 선택사항: Redis 관리 도구
  redis-commander:
    image: rediscommander/redis-commander:latest
    container_name: lunch_app_redis_commander
    ports:
      - "8081:8081"
    environment:
      - REDIS_HOSTS=local:redis:6379
    depends_on:
      - redis
    restart: unless-stopped

volumes:
  redis_data:
