"""Remove test field from User model

Revision ID: 29c6da1f68ba
Revises: 87bade1fb681
Create Date: 2025-09-02 21:59:34.808352

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '29c6da1f68ba'
down_revision = '87bade1fb681'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('test_field')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('test_field', sa.VARCHAR(length=100), nullable=True))

    # ### end Alembic commands ###
