"""party datetime columns migration

Revision ID: 88b198af2208
Revises: 29c6da1f68ba
Create Date: 2025-09-09 21:22:59.575964

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88b198af2208'
down_revision = '29c6da1f68ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('badge_name', sa.String(length=50), nullable=False),
    sa.Column('badge_icon', sa.String(length=20), nullable=False),
    sa.Column('badge_color', sa.String(length=10), nullable=True),
    sa.Column('requirement_type', sa.String(length=50), nullable=False),
    sa.Column('requirement_count', sa.Integer(), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('category_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('category', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_type', sa.String(length=20), nullable=False),
    sa.Column('chat_id', sa.Integer(), nullable=False),
    sa.Column('sender_employee_id', sa.String(length=50), nullable=False),
    sa.Column('sender_nickname', sa.String(length=50), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('daily_recommendation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.String(length=20), nullable=False),
    sa.Column('group_members', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('friendships',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.String(length=50), nullable=False),
    sa.Column('receiver_id', sa.String(length=50), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('lunch_proposal',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposer_id', sa.String(length=50), nullable=False),
    sa.Column('recipient_ids', sa.Text(), nullable=False),
    sa.Column('proposed_date', sa.String(length=20), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('magic_link_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_used', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_magic_link_tokens_email'), 'magic_link_tokens', ['email'], unique=False)
    op.create_index(op.f('ix_magic_link_tokens_token_hash'), 'magic_link_tokens', ['token_hash'], unique=True)
    op.create_table('match_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('requester_id', sa.String(length=50), nullable=False),
    sa.Column('target_user_id', sa.String(length=50), nullable=True),
    sa.Column('preferred_date', sa.String(length=20), nullable=True),
    sa.Column('preferred_time', sa.String(length=10), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('matched_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('notification',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('type', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('related_id', sa.Integer(), nullable=True),
    sa.Column('related_type', sa.String(length=50), nullable=True),
    sa.Column('is_read', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('offline_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('data_type', sa.String(length=50), nullable=False),
    sa.Column('data_json', sa.Text(), nullable=False),
    sa.Column('last_sync', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('host_employee_id', sa.String(length=50), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('restaurant_name', sa.String(length=100), nullable=False),
    sa.Column('restaurant_address', sa.String(length=200), nullable=True),
    sa.Column('party_date', sa.Date(), nullable=False),
    sa.Column('party_time', sa.Time(), nullable=False),
    sa.Column('meeting_location', sa.String(length=200), nullable=True),
    sa.Column('max_members', sa.Integer(), nullable=False),
    sa.Column('is_from_match', sa.Boolean(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_host_employee_id', 'party', ['host_employee_id'], unique=False)
    op.create_index('idx_party_date', 'party', ['party_date'], unique=False)
    op.create_index('idx_party_restaurant', 'party', ['restaurant_name'], unique=False)
    op.create_table('restaurant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('address', sa.String(length=500), nullable=True),
    sa.Column('category', sa.String(length=100), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_activity',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('activity_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('points_earned', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_parties_joined', sa.Integer(), nullable=True),
    sa.Column('total_reviews_written', sa.Integer(), nullable=True),
    sa.Column('total_friends_added', sa.Integer(), nullable=True),
    sa.Column('favorite_restaurant_category', sa.String(length=50), nullable=True),
    sa.Column('average_rating_given', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_preference',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('food_preferences', sa.String(length=200), nullable=True),
    sa.Column('lunch_style', sa.String(length=200), nullable=True),
    sa.Column('max_distance', sa.Integer(), nullable=True),
    sa.Column('budget_range', sa.String(length=50), nullable=True),
    sa.Column('preferred_time', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('points', sa.Integer(), nullable=True),
    sa.Column('profile_image', sa.String(length=255), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('age_group', sa.String(length=20), nullable=True),
    sa.Column('main_dish_genre', sa.String(length=100), nullable=True),
    sa.Column('lunch_preference', sa.String(length=200), nullable=True),
    sa.Column('allergies', sa.String(length=200), nullable=True),
    sa.Column('preferred_time', sa.String(length=50), nullable=True),
    sa.Column('food_preferences', sa.String(length=200), nullable=True),
    sa.Column('frequent_areas', sa.String(length=200), nullable=True),
    sa.Column('notification_settings', sa.String(length=200), nullable=True),
    sa.Column('total_points', sa.Integer(), nullable=True),
    sa.Column('current_level', sa.Integer(), nullable=True),
    sa.Column('current_badge', sa.String(length=50), nullable=True),
    sa.Column('consecutive_login_days', sa.Integer(), nullable=True),
    sa.Column('last_login_date', sa.Date(), nullable=True),
    sa.Column('matching_status', sa.String(length=20), nullable=True),
    sa.Column('match_request_time', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('voting_session',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('chat_room_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=100), nullable=False),
    sa.Column('restaurant_name', sa.String(length=100), nullable=True),
    sa.Column('restaurant_address', sa.String(length=200), nullable=True),
    sa.Column('meeting_location', sa.String(length=200), nullable=True),
    sa.Column('meeting_time', sa.String(length=10), nullable=True),
    sa.Column('participants', sa.Text(), nullable=False),
    sa.Column('available_dates', sa.Text(), nullable=True),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_by', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('confirmed_date', sa.String(length=20), nullable=True),
    sa.Column('confirmed_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_message_read',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('message_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('read_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['message_id'], ['chat_message.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dangol_pot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=50), nullable=True),
    sa.Column('host_id', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['host_id'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dangolpot_category', 'dangol_pot', ['category'], unique=False)
    op.create_index('idx_dangolpot_host', 'dangol_pot', ['host_id'], unique=False)
    op.create_table('date_vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_session_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.String(length=50), nullable=False),
    sa.Column('voted_date', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('match',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('match_request_id', sa.Integer(), nullable=False),
    sa.Column('user1_id', sa.String(length=50), nullable=False),
    sa.Column('user2_id', sa.String(length=50), nullable=False),
    sa.Column('matched_date', sa.String(length=20), nullable=True),
    sa.Column('matched_time', sa.String(length=10), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['match_request_id'], ['match_request.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('party_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.Column('is_host', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_member_party', 'party_member', ['employee_id', 'party_id'], unique=False)
    op.create_index('idx_party_member', 'party_member', ['party_id', 'employee_id'], unique=False)
    op.create_table('proposal_acceptance',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('proposal_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('accepted_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['proposal_id'], ['lunch_proposal.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('refresh_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.DateTime(), nullable=False),
    sa.Column('is_revoked', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_refresh_tokens_token_hash'), 'refresh_tokens', ['token_hash'], unique=True)
    op.create_table('restaurant_analytics',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('total_visits', sa.Integer(), nullable=True),
    sa.Column('total_reviews', sa.Integer(), nullable=True),
    sa.Column('average_rating', sa.Float(), nullable=True),
    sa.Column('total_likes', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('request_type', sa.String(length=20), nullable=False),
    sa.Column('restaurant_name', sa.String(length=100), nullable=True),
    sa.Column('restaurant_address', sa.String(length=200), nullable=True),
    sa.Column('restaurant_id', sa.Integer(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('requester_id', sa.String(length=50), nullable=False),
    sa.Column('requester_nickname', sa.String(length=50), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('approved_at', sa.DateTime(), nullable=True),
    sa.Column('approved_by', sa.String(length=50), nullable=True),
    sa.Column('rejection_reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('restaurant_visit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('visit_date', sa.Date(), nullable=False),
    sa.Column('visit_time', sa.String(length=10), nullable=True),
    sa.Column('party_size', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('review',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('nickname', sa.String(length=50), nullable=False),
    sa.Column('rating', sa.Integer(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('photo_url', sa.String(length=255), nullable=True),
    sa.Column('tags', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('revoked_tokens',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('token_hash', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_revoked_tokens_token_hash'), 'revoked_tokens', ['token_hash'], unique=True)
    op.create_table('user_badge',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('badge_id', sa.Integer(), nullable=False),
    sa.Column('earned_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['badge_id'], ['badge.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_favorite',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('restaurant_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['restaurant_id'], ['restaurant.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('voting_option',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_session_id', sa.Integer(), nullable=False),
    sa.Column('option_text', sa.String(length=200), nullable=False),
    sa.Column('option_type', sa.String(length=50), nullable=False),
    sa.Column('votes_count', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_room',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('type', sa.String(length=20), nullable=False),
    sa.Column('party_id', sa.Integer(), nullable=True),
    sa.Column('dangolpot_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dangolpot_id'], ['dangol_pot.id'], ),
    sa.ForeignKeyConstraint(['party_id'], ['party.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('dangol_pot_member',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('dangolpot_id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['dangolpot_id'], ['dangol_pot.id'], ),
    sa.ForeignKeyConstraint(['employee_id'], ['users.employee_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_dangolpot_member', 'dangol_pot_member', ['dangolpot_id', 'employee_id'], unique=False)
    op.create_index('idx_member_dangolpot', 'dangol_pot_member', ['employee_id', 'dangolpot_id'], unique=False)
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('voting_session_id', sa.Integer(), nullable=False),
    sa.Column('voter_id', sa.String(length=50), nullable=False),
    sa.Column('option_id', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['option_id'], ['voting_option.id'], ),
    sa.ForeignKeyConstraint(['voting_session_id'], ['voting_session.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('chat_participant',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('room_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.String(length=50), nullable=False),
    sa.Column('joined_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['room_id'], ['chat_room.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chat_participant')
    op.drop_table('vote')
    op.drop_index('idx_member_dangolpot', table_name='dangol_pot_member')
    op.drop_index('idx_dangolpot_member', table_name='dangol_pot_member')
    op.drop_table('dangol_pot_member')
    op.drop_table('chat_room')
    op.drop_table('voting_option')
    op.drop_table('user_favorite')
    op.drop_table('user_badge')
    op.drop_index(op.f('ix_revoked_tokens_token_hash'), table_name='revoked_tokens')
    op.drop_table('revoked_tokens')
    op.drop_table('review')
    op.drop_table('restaurant_visit')
    op.drop_table('restaurant_request')
    op.drop_table('restaurant_favorite')
    op.drop_table('restaurant_analytics')
    op.drop_index(op.f('ix_refresh_tokens_token_hash'), table_name='refresh_tokens')
    op.drop_table('refresh_tokens')
    op.drop_table('proposal_acceptance')
    op.drop_index('idx_party_member', table_name='party_member')
    op.drop_index('idx_member_party', table_name='party_member')
    op.drop_table('party_member')
    op.drop_table('match')
    op.drop_table('date_vote')
    op.drop_index('idx_dangolpot_host', table_name='dangol_pot')
    op.drop_index('idx_dangolpot_category', table_name='dangol_pot')
    op.drop_table('dangol_pot')
    op.drop_table('chat_message_read')
    op.drop_table('voting_session')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_table('user_preference')
    op.drop_table('user_analytics')
    op.drop_table('user_activity')
    op.drop_table('restaurant')
    op.drop_index('idx_party_restaurant', table_name='party')
    op.drop_index('idx_party_date', table_name='party')
    op.drop_index('idx_host_employee_id', table_name='party')
    op.drop_table('party')
    op.drop_table('offline_data')
    op.drop_table('notification')
    op.drop_table('match_request')
    op.drop_index(op.f('ix_magic_link_tokens_token_hash'), table_name='magic_link_tokens')
    op.drop_index(op.f('ix_magic_link_tokens_email'), table_name='magic_link_tokens')
    op.drop_table('magic_link_tokens')
    op.drop_table('lunch_proposal')
    op.drop_table('friendships')
    op.drop_table('daily_recommendation')
    op.drop_table('chat_message')
    op.drop_table('category_activity')
    op.drop_table('badge')
    # ### end Alembic commands ###
