"""Add password authentication fields to User model

Revision ID: add_password_auth_fields
Revises: 88b198af2208
Create Date: 2025-09-25 22:30:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_password_auth_fields'
down_revision = '88b198af2208'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('login_method', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('last_password_change', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('failed_login_attempts', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('account_locked_until', sa.DateTime(), nullable=True))
    
    # Set default values for existing users
    op.execute("UPDATE users SET login_method = 'magic_link' WHERE login_method IS NULL")
    op.execute("UPDATE users SET failed_login_attempts = 0 WHERE failed_login_attempts IS NULL")
    
    # Make login_method NOT NULL after setting defaults
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('login_method', nullable=False)
        batch_op.alter_column('failed_login_attempts', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('account_locked_until')
        batch_op.drop_column('failed_login_attempts')
        batch_op.drop_column('last_password_change')
        batch_op.drop_column('login_method')
        batch_op.drop_column('password_hash')
    # ### end Alembic commands ###
