"""add title column to chat_room

Revision ID: add_title_column_to_chat_room
Revises: 29c6da1f68ba
Create Date: 2025-09-18 13:57:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'add_title_column_to_chat_room'
down_revision = '29c6da1f68ba'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('chat_room', sa.Column('title', sa.String(length=100), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('chat_room', 'title')
    # ### end Alembic commands ###
